### ISSUE TITLE
Filament Sensor of Mega S is ignored

### ISSUE THREAD

**Issue by NilsRo** [davidramiro/Marlin-Ai3M#103] opened 2020-12-10 18:03 UTC
**Describe the bug**
A filament Runout is ignored using Octoprint and  Marlin with Mega S printer. I am not sure if it is the firmware configuration or perhaps octoprint but from the configuration in the sourcecode the runout sensor seems inactive.

**To Reproduce**
1. Print with less filament
2. Runout will not stop printing

**Expected behavior**
A filament runout should pause printing

**Printer (please complete the following information):**
 - Firmware version: 1.1.9.1
 - Printing method: OctoPrint, Cura
 - Model: Mega-S

**M503 Output**
Send: M503
Recv: echo:  G21    ; (mm)
Recv: 
Recv: echo:Filament settings: Disabled
Recv: echo:  M200 D1.75
Recv: echo:  M200 D0
Recv: echo:Steps per unit:
Recv: echo:  M92 X80.00 Y80.00 Z400.00 E425.53
Recv: echo:Maximum feedrates (units/s):
Recv: echo:  M203 X500.00 Y500.00 Z6.00 E60.00
Recv: echo:Maximum Acceleration (units/s2):
Recv: echo:  M201 X3000 Y2000 Z60 E10000
Recv: echo:Acceleration (units/s2): P<print_accel> R<retract_accel> T<travel_accel>
Recv: echo:  M204 P4000.00 R3000.00 T4000.00
Recv: echo:Advanced: Q<min_segment_time_us> S<min_feedrate> T<min_travel_feedrate> X<max_x_jerk> Y<max_y_jerk> Z<max_z_jerk> E<max_e_jerk>
Recv: echo:  M205 Q20000 S0.00 T0.00 X20.00 Y20.00 Z0.40 E5.00
Recv: echo:Home offset:
Recv: echo:  M206 X0.00 Y0.00 Z0.00
Recv: echo:Mesh Bed Leveling:
Recv: echo:  M420 S0 Z0.00
Recv: echo:  G29 S3 X1 Y1 Z-0.08000
Recv: echo:  G29 S3 X2 Y1 Z-0.12000
Recv: echo:  G29 S3 X3 Y1 Z-0.12000
Recv: echo:  G29 S3 X4 Y1 Z-0.16000
Recv: echo:  G29 S3 X5 Y1 Z-0.22000
Recv: echo:  G29 S3 X1 Y2 Z-0.14000
Recv: echo:  G29 S3 X2 Y2 Z-0.10000
Recv: echo:  G29 S3 X3 Y2 Z-0.06000
Recv: echo:  G29 S3 X4 Y2 Z-0.10000
Recv: echo:  G29 S3 X5 Y2 Z-0.14000
Recv: echo:  G29 S3 X1 Y3 Z-0.16000
Recv: echo:  G29 S3 X2 Y3 Z-0.10000
Recv: echo:  G29 S3 X3 Y3 Z-0.06000
Recv: echo:  G29 S3 X4 Y3 Z-0.06000
Recv: echo:  G29 S3 X5 Y3 Z-0.10000
Recv: echo:  G29 S3 X1 Y4 Z-0.20000
Recv: echo:  G29 S3 X2 Y4 Z-0.14000
Recv: echo:  G29 S3 X3 Y4 Z-0.10000
Recv: echo:  G29 S3 X4 Y4 Z-0.08000
Recv: echo:  G29 S3 X5 Y4 Z-0.10000
Recv: echo:  G29 S3 X1 Y5 Z-0.20000
Recv: echo:  G29 S3 X2 Y5 Z-0.16000
Recv: echo:  G29 S3 X3 Y5 Z-0.12000
Recv: echo:  G29 S3 X4 Y5 Z-0.12000
Recv: echo:  G29 S3 X5 Y5 Z-0.14000
Recv: echo:Endstop adjustment:
Recv: echo:  M666 Z0.00
Recv: echo:PID settings:
Recv: echo:  M301 P16.30 I1.14 D58.42
Recv: echo:  M304 P222.44 I43.80 D282.45
Recv: echo:Linear Advance:
Recv: echo:  M900 K0.00
Recv: echo:Filament load/unload lengths:
Recv: echo:  M603 L538.00 U555.00
Recv: ok

**Comment by davidramiro** [comment] 2020-12-10 18:20
Duplicate of #96

**Closed by davidramiro** 2020-12-10 18:20 UTC
Labels: bug
